=head1 NAME

chuse - Portage USE flags manager

=head1 SYNOPSIS

S<chuse I<atom> [[I<modifier>]I<flag> ...] [--because I<reason>]>
S<chuse I<atom>>
S<chuse (-h|--help)>
S<chuse (-v|--version)>
S<chuse --dump>
S<chuse --load I<file>>

=head1 DESCRIPTION

Chuse stands for CHange USE. This is a Portage tool for managing your local USE
flags (ie. set within /etc/portage/package.use).

In contrast to several equivalents, it is designed with a very specific goal:
Make your I</etc/portage/package.use> management easier. This means chuse does
not handle other I<package.*> and focuses on I<package.use>.

=head1 OPTIONS

=over

=item I<atom>

[I<version-selector>]I<ebuild-cat>/I<ebuild-pkg>[-I<version>][:I<slot>]

Obviously, I<version-selector> and I<version> should never be set without the
other.

=item I<version-selector>

One of: =, >, <, >, >=, <=.

=item I<ebuild-cat>

An ebuild category (validity won't be checked)

=item I<ebuild-pkg>

An ebuild package (validity won't be checked)

=item I<version>

A version of the underlying package (validity won't be checked).

=item I<slot>

A slot of the underlying package (validity won't be checked)

=item I<modifier>

One of: +, -, %. (% means reset default). If omitted, + is assumed.

=item I<flag>

A USE flag (validity won't be checked).

=item I<reason>

The reason why you changed these USE flags (so that you remember why you set
this and if you can reset default in the future for instance).

=item B<--dump>

Print all contents of /etc/portage/package.use

=item B<-h --help>

Print help

=item B<--load> I<file>

Load a backup file to the /etc/portage/package.use hierarchy.

=item B<-v --version>

Print version information

=back

=head1 EXAMPLES

By default, chuse uses the following hierarchy pattern:

    /etc/portage/package.use/I<cat-name>/I<pkg-name>

That is, one directory per package category, one file per package.

If you don't use this hierarchy pattern and want to adopt it:

    chuse --dump > /root/package.use.bak # Concat all your rules in one file
    chuse --load /root/package.use.back # Export the backup to the new hierarchy

If you cant to setup your own hierarchy pattern, you can change the pattern by
explicitely setting the PACKAGE_USE_FILE_PATTERN environment variable (eg. in
your bashrc).

    PACKAGE_USE_FILE_PATTERN="/etc/portage/package.use" # All in one file
    PACKAGE_USE_FILE_PATTERN="/etc/portage/package.use/%(cat)s" # One file per category
    PACKAGE_USE_FILE_PATTERN="/etc/portage/package.use/%(cat)s/%(pkg)s" # This is the default
    PACKAGE_USE_FILE_PATTERN="/etc/portage/package.use/chuse" # One file dedicated to chuse

Add system-cairo, remove system-icu and reset system-jpeg for firefox >= 37.0.1:
    $ sudo chuse ">=www-client/firefox-37.0.1" +system-cairo -system-icu %system-jpeg

Add offensive for sudo:

    $ sudo chuse app-admin/sudo offensive --because much cooler

Show the flags you altered for sudo:

    $ chuse app-admin/sudo
    # [2015-04-18T11:54] Unset sendmail
    # [2015-04-18T11:56] Set offensive
    # much cooler
    app-admin/sudo offensive -sendmail

=head1 BUGS

Please report bugs on github L<https://github.com/apinsard/chuse/issues>

=head1 AUTHOR

Antoine Pinsard <antoine.pinsard@gmail.com>

=head1 SEE ALSO

L<portage(5)>
